name: Build and Deploy Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/tomcher/pinavto:latest
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy to Remote Server using SSH
        env:
          HOST: ${{ vars.DEPLOY_HOST }}
          USER: ${{ vars.DEPLOY_USER }}
        run: |
          ssh $USER@$HOST -o "StrictHostKeyChecking no" <<EOF
            docker login ghcr.io -u ${{ github.repository_owner }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            mkdir -p public
            docker pull ghcr.io/tomcher/pinavto:latest
            docker stop pinavto || true
            docker rm pinavto || true
            docker run -d -p "3000:3000" -v ./public:/app/public -e SITE_URL=${{vars.SITE_URL}} -e ELASTIC_HOST=${{vars.ELASTIC_HOST}} -e ELASTIC_KEY=${{ secrets.ELASTIC_KEY }} --name pinavto ghcr.io/tomcher/pinavto:latest
          EOF