name: Build and Deploy Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/tomcher/pinavto:latest
      - name: Deploy to Remote Server using SSH
        env:
          HOST: ${{ vars.DEPLOY_HOST }}
          USER: ${{ vars.DEPLOY_USER }}
          PORT: 22
          KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" | ssh $USER@$HOST -p $PORT -i /dev/stdin -o "StrictHostKeyChecking no" <<EOF
            docker login ghcr.io -u ${{ github.repository_owner }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ghcr.io/tomcher/pinavto:latest
            docker stop pinavto || true
            docker rm pinavto || true
            docker run -d --name pinavto ghcr.io/tomcher/pinavto:latest
          EOF